#
###################################
# Site wide configuration
####################################
#
title: 喵喵清吟 | 爱菜家希望之神小飞鸟官方博客
description: '爱菜家、希望之神小飞鸟官方博客'
url: https://blog.mana.love
avatar: https://www.tuchuang001.com/images/2017/05/20/site-avatar.png
favicon: https://www.tuchuang001.com/images/2017/05/20/favicon.png
begin_year: 2015
copyname: 喵喵清吟,blog.mana.love
baidu-analysis: 9e7b394e0b9f2ed7bbe4edf5607e7dad
yungentie-productkey: 86a52c1e48c0450385a25e49e7c984cd
yungentie-loader: aHR0cHM6Ly9hcGkuZ2VudGllLjE2My5jb20vcGMvbGl2ZXNjcmlwdC5odG1s

#

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:year/:month/:day/:title.html
timezone:          Asia/Shanghai

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: 小飞鸟
  avatar: avatar_13.png
  job: "爱菜家、希望之神"
  bio: "爱菜、爱菜、爱菜"

  github: ashidamana #username
  weibo: flyerangel #username
#  facebook: streamelody #username
  email: flyer@mana.love
#  duoshuo: streamelody #多说域名

#  google:
#    plus: #username
#    analytics: UA-62251910-1
#    verify:
#    ad-client:
#    ad-slot:
#  bing-verify:
#  disqus-shortname: #username
#  twitter:  #username
#  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
#  linkedin: #username
#  xing: #username
#  instagram: #username
#  lastfm: #username
#  tumblr: #username
#  pinterest: #username
#  foursquare: #username
#  steam: #username
#  dribbble: #username
#  youtube: #username
#  soundcloud: #username
#  flickr: #username
#  codepen: #username
